// Code generated by protoc-gen-go. DO NOT EDIT.
// source: agent.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type WeighingScaleStatus int32

const (
	WeighingScaleStatus_OFFLINE        WeighingScaleStatus = 0
	WeighingScaleStatus_EMPTY          WeighingScaleStatus = 1
	WeighingScaleStatus_IN_TRANSACTION WeighingScaleStatus = 2
	WeighingScaleStatus_HW_ERROR       WeighingScaleStatus = 3
	WeighingScaleStatus_ALERT          WeighingScaleStatus = 4
)

var WeighingScaleStatus_name = map[int32]string{
	0: "OFFLINE",
	1: "EMPTY",
	2: "IN_TRANSACTION",
	3: "HW_ERROR",
	4: "ALERT",
}

var WeighingScaleStatus_value = map[string]int32{
	"OFFLINE":        0,
	"EMPTY":          1,
	"IN_TRANSACTION": 2,
	"HW_ERROR":       3,
	"ALERT":          4,
}

func (x WeighingScaleStatus) String() string {
	return proto.EnumName(WeighingScaleStatus_name, int32(x))
}

func (WeighingScaleStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{0}
}

type AgentStatus int32

const (
	AgentStatus_CLOSED       AgentStatus = 0
	AgentStatus_SYSTEM_ERROR AgentStatus = 1
	AgentStatus_OPEN         AgentStatus = 2
)

var AgentStatus_name = map[int32]string{
	0: "CLOSED",
	1: "SYSTEM_ERROR",
	2: "OPEN",
}

var AgentStatus_value = map[string]int32{
	"CLOSED":       0,
	"SYSTEM_ERROR": 1,
	"OPEN":         2,
}

func (x AgentStatus) String() string {
	return proto.EnumName(AgentStatus_name, int32(x))
}

func (AgentStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{1}
}

type DishBindStatus int32

const (
	DishBindStatus_NEW            DishBindStatus = 0
	DishBindStatus_ALREADY_EXISTS DishBindStatus = 1
)

var DishBindStatus_name = map[int32]string{
	0: "NEW",
	1: "ALREADY_EXISTS",
}

var DishBindStatus_value = map[string]int32{
	"NEW":            0,
	"ALREADY_EXISTS": 1,
}

func (x DishBindStatus) String() string {
	return proto.EnumName(DishBindStatus_name, int32(x))
}

func (DishBindStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{2}
}

// 称重台签到请求
type WeighingScaleLogin struct {
	Termno               string              `protobuf:"bytes,1,opt,name=termno,proto3" json:"termno,omitempty"`
	Timestamp            string              `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Status               WeighingScaleStatus `protobuf:"varint,3,opt,name=status,proto3,enum=WeighingScaleStatus" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *WeighingScaleLogin) Reset()         { *m = WeighingScaleLogin{} }
func (m *WeighingScaleLogin) String() string { return proto.CompactTextString(m) }
func (*WeighingScaleLogin) ProtoMessage()    {}
func (*WeighingScaleLogin) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{0}
}

func (m *WeighingScaleLogin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WeighingScaleLogin.Unmarshal(m, b)
}
func (m *WeighingScaleLogin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WeighingScaleLogin.Marshal(b, m, deterministic)
}
func (m *WeighingScaleLogin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WeighingScaleLogin.Merge(m, src)
}
func (m *WeighingScaleLogin) XXX_Size() int {
	return xxx_messageInfo_WeighingScaleLogin.Size(m)
}
func (m *WeighingScaleLogin) XXX_DiscardUnknown() {
	xxx_messageInfo_WeighingScaleLogin.DiscardUnknown(m)
}

var xxx_messageInfo_WeighingScaleLogin proto.InternalMessageInfo

func (m *WeighingScaleLogin) GetTermno() string {
	if m != nil {
		return m.Termno
	}
	return ""
}

func (m *WeighingScaleLogin) GetTimestamp() string {
	if m != nil {
		return m.Timestamp
	}
	return ""
}

func (m *WeighingScaleLogin) GetStatus() WeighingScaleStatus {
	if m != nil {
		return m.Status
	}
	return WeighingScaleStatus_OFFLINE
}

// 称重台签到应答
type WeighingScaleLoginResponse struct {
	SystemTimestamp      string      `protobuf:"bytes,1,opt,name=system_timestamp,json=systemTimestamp,proto3" json:"system_timestamp,omitempty"`
	AccessKey            string      `protobuf:"bytes,2,opt,name=access_key,json=accessKey,proto3" json:"access_key,omitempty"`
	SystemStatus         AgentStatus `protobuf:"varint,3,opt,name=system_status,json=systemStatus,proto3,enum=AgentStatus" json:"system_status,omitempty"`
	DeviceId             int32       `protobuf:"varint,4,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	HeartGap             int32       `protobuf:"varint,5,opt,name=heart_gap,json=heartGap,proto3" json:"heart_gap,omitempty"`
	FoodVerNo            string      `protobuf:"bytes,6,opt,name=food_ver_no,json=foodVerNo,proto3" json:"food_ver_no,omitempty"`
	ParaVerNo            int32       `protobuf:"varint,7,opt,name=para_ver_no,json=paraVerNo,proto3" json:"para_ver_no,omitempty"`
	Retjson              string      `protobuf:"bytes,8,opt,name=retjson,proto3" json:"retjson,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *WeighingScaleLoginResponse) Reset()         { *m = WeighingScaleLoginResponse{} }
func (m *WeighingScaleLoginResponse) String() string { return proto.CompactTextString(m) }
func (*WeighingScaleLoginResponse) ProtoMessage()    {}
func (*WeighingScaleLoginResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{1}
}

func (m *WeighingScaleLoginResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WeighingScaleLoginResponse.Unmarshal(m, b)
}
func (m *WeighingScaleLoginResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WeighingScaleLoginResponse.Marshal(b, m, deterministic)
}
func (m *WeighingScaleLoginResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WeighingScaleLoginResponse.Merge(m, src)
}
func (m *WeighingScaleLoginResponse) XXX_Size() int {
	return xxx_messageInfo_WeighingScaleLoginResponse.Size(m)
}
func (m *WeighingScaleLoginResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_WeighingScaleLoginResponse.DiscardUnknown(m)
}

var xxx_messageInfo_WeighingScaleLoginResponse proto.InternalMessageInfo

func (m *WeighingScaleLoginResponse) GetSystemTimestamp() string {
	if m != nil {
		return m.SystemTimestamp
	}
	return ""
}

func (m *WeighingScaleLoginResponse) GetAccessKey() string {
	if m != nil {
		return m.AccessKey
	}
	return ""
}

func (m *WeighingScaleLoginResponse) GetSystemStatus() AgentStatus {
	if m != nil {
		return m.SystemStatus
	}
	return AgentStatus_CLOSED
}

func (m *WeighingScaleLoginResponse) GetDeviceId() int32 {
	if m != nil {
		return m.DeviceId
	}
	return 0
}

func (m *WeighingScaleLoginResponse) GetHeartGap() int32 {
	if m != nil {
		return m.HeartGap
	}
	return 0
}

func (m *WeighingScaleLoginResponse) GetFoodVerNo() string {
	if m != nil {
		return m.FoodVerNo
	}
	return ""
}

func (m *WeighingScaleLoginResponse) GetParaVerNo() int32 {
	if m != nil {
		return m.ParaVerNo
	}
	return 0
}

func (m *WeighingScaleLoginResponse) GetRetjson() string {
	if m != nil {
		return m.Retjson
	}
	return ""
}

// 称重台心跳请求
type WeighingScaleHeartBeat struct {
	Termno               string              `protobuf:"bytes,1,opt,name=termno,proto3" json:"termno,omitempty"`
	AccessKey            string              `protobuf:"bytes,2,opt,name=access_key,json=accessKey,proto3" json:"access_key,omitempty"`
	Status               WeighingScaleStatus `protobuf:"varint,3,opt,name=status,proto3,enum=WeighingScaleStatus" json:"status,omitempty"`
	SoldFoodId           string              `protobuf:"bytes,4,opt,name=sold_food_id,json=soldFoodId,proto3" json:"sold_food_id,omitempty"`
	SoldFoodUpdatetime   string              `protobuf:"bytes,5,opt,name=sold_food_updatetime,json=soldFoodUpdatetime,proto3" json:"sold_food_updatetime,omitempty"`
	FoodWeight           int32               `protobuf:"varint,6,opt,name=food_weight,json=foodWeight,proto3" json:"food_weight,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *WeighingScaleHeartBeat) Reset()         { *m = WeighingScaleHeartBeat{} }
func (m *WeighingScaleHeartBeat) String() string { return proto.CompactTextString(m) }
func (*WeighingScaleHeartBeat) ProtoMessage()    {}
func (*WeighingScaleHeartBeat) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{2}
}

func (m *WeighingScaleHeartBeat) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WeighingScaleHeartBeat.Unmarshal(m, b)
}
func (m *WeighingScaleHeartBeat) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WeighingScaleHeartBeat.Marshal(b, m, deterministic)
}
func (m *WeighingScaleHeartBeat) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WeighingScaleHeartBeat.Merge(m, src)
}
func (m *WeighingScaleHeartBeat) XXX_Size() int {
	return xxx_messageInfo_WeighingScaleHeartBeat.Size(m)
}
func (m *WeighingScaleHeartBeat) XXX_DiscardUnknown() {
	xxx_messageInfo_WeighingScaleHeartBeat.DiscardUnknown(m)
}

var xxx_messageInfo_WeighingScaleHeartBeat proto.InternalMessageInfo

func (m *WeighingScaleHeartBeat) GetTermno() string {
	if m != nil {
		return m.Termno
	}
	return ""
}

func (m *WeighingScaleHeartBeat) GetAccessKey() string {
	if m != nil {
		return m.AccessKey
	}
	return ""
}

func (m *WeighingScaleHeartBeat) GetStatus() WeighingScaleStatus {
	if m != nil {
		return m.Status
	}
	return WeighingScaleStatus_OFFLINE
}

func (m *WeighingScaleHeartBeat) GetSoldFoodId() string {
	if m != nil {
		return m.SoldFoodId
	}
	return ""
}

func (m *WeighingScaleHeartBeat) GetSoldFoodUpdatetime() string {
	if m != nil {
		return m.SoldFoodUpdatetime
	}
	return ""
}

func (m *WeighingScaleHeartBeat) GetFoodWeight() int32 {
	if m != nil {
		return m.FoodWeight
	}
	return 0
}

type WeighingParam struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WeighingParam) Reset()         { *m = WeighingParam{} }
func (m *WeighingParam) String() string { return proto.CompactTextString(m) }
func (*WeighingParam) ProtoMessage()    {}
func (*WeighingParam) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{3}
}

func (m *WeighingParam) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WeighingParam.Unmarshal(m, b)
}
func (m *WeighingParam) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WeighingParam.Marshal(b, m, deterministic)
}
func (m *WeighingParam) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WeighingParam.Merge(m, src)
}
func (m *WeighingParam) XXX_Size() int {
	return xxx_messageInfo_WeighingParam.Size(m)
}
func (m *WeighingParam) XXX_DiscardUnknown() {
	xxx_messageInfo_WeighingParam.DiscardUnknown(m)
}

var xxx_messageInfo_WeighingParam proto.InternalMessageInfo

func (m *WeighingParam) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *WeighingParam) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

// 称重台心跳应答
type WeighingScaleResponse struct {
	SystemStatus         AgentStatus      `protobuf:"varint,1,opt,name=system_status,json=systemStatus,proto3,enum=AgentStatus" json:"system_status,omitempty"`
	SystemTimestamp      string           `protobuf:"bytes,2,opt,name=system_timestamp,json=systemTimestamp,proto3" json:"system_timestamp,omitempty"`
	SoldFoodId           string           `protobuf:"bytes,3,opt,name=sold_food_id,json=soldFoodId,proto3" json:"sold_food_id,omitempty"`
	SoldFoodUpdatetime   string           `protobuf:"bytes,4,opt,name=sold_food_updatetime,json=soldFoodUpdatetime,proto3" json:"sold_food_updatetime,omitempty"`
	SoftVersion          string           `protobuf:"bytes,5,opt,name=soft_version,json=softVersion,proto3" json:"soft_version,omitempty"`
	HeartGap             int32            `protobuf:"varint,6,opt,name=heart_gap,json=heartGap,proto3" json:"heart_gap,omitempty"`
	FoodVerNo            string           `protobuf:"bytes,7,opt,name=food_ver_no,json=foodVerNo,proto3" json:"food_ver_no,omitempty"`
	ParaVerNo            int32            `protobuf:"varint,8,opt,name=para_ver_no,json=paraVerNo,proto3" json:"para_ver_no,omitempty"`
	Alarm                int32            `protobuf:"varint,9,opt,name=alarm,proto3" json:"alarm,omitempty"`
	Retjson              string           `protobuf:"bytes,10,opt,name=retjson,proto3" json:"retjson,omitempty"`
	Params               []*WeighingParam `protobuf:"bytes,11,rep,name=params,proto3" json:"params,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *WeighingScaleResponse) Reset()         { *m = WeighingScaleResponse{} }
func (m *WeighingScaleResponse) String() string { return proto.CompactTextString(m) }
func (*WeighingScaleResponse) ProtoMessage()    {}
func (*WeighingScaleResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{4}
}

func (m *WeighingScaleResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WeighingScaleResponse.Unmarshal(m, b)
}
func (m *WeighingScaleResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WeighingScaleResponse.Marshal(b, m, deterministic)
}
func (m *WeighingScaleResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WeighingScaleResponse.Merge(m, src)
}
func (m *WeighingScaleResponse) XXX_Size() int {
	return xxx_messageInfo_WeighingScaleResponse.Size(m)
}
func (m *WeighingScaleResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_WeighingScaleResponse.DiscardUnknown(m)
}

var xxx_messageInfo_WeighingScaleResponse proto.InternalMessageInfo

func (m *WeighingScaleResponse) GetSystemStatus() AgentStatus {
	if m != nil {
		return m.SystemStatus
	}
	return AgentStatus_CLOSED
}

func (m *WeighingScaleResponse) GetSystemTimestamp() string {
	if m != nil {
		return m.SystemTimestamp
	}
	return ""
}

func (m *WeighingScaleResponse) GetSoldFoodId() string {
	if m != nil {
		return m.SoldFoodId
	}
	return ""
}

func (m *WeighingScaleResponse) GetSoldFoodUpdatetime() string {
	if m != nil {
		return m.SoldFoodUpdatetime
	}
	return ""
}

func (m *WeighingScaleResponse) GetSoftVersion() string {
	if m != nil {
		return m.SoftVersion
	}
	return ""
}

func (m *WeighingScaleResponse) GetHeartGap() int32 {
	if m != nil {
		return m.HeartGap
	}
	return 0
}

func (m *WeighingScaleResponse) GetFoodVerNo() string {
	if m != nil {
		return m.FoodVerNo
	}
	return ""
}

func (m *WeighingScaleResponse) GetParaVerNo() int32 {
	if m != nil {
		return m.ParaVerNo
	}
	return 0
}

func (m *WeighingScaleResponse) GetAlarm() int32 {
	if m != nil {
		return m.Alarm
	}
	return 0
}

func (m *WeighingScaleResponse) GetRetjson() string {
	if m != nil {
		return m.Retjson
	}
	return ""
}

func (m *WeighingScaleResponse) GetParams() []*WeighingParam {
	if m != nil {
		return m.Params
	}
	return nil
}

// 绑定餐盘请求
type BindDishRequest struct {
	DishId               string   `protobuf:"bytes,1,opt,name=dish_id,json=dishId,proto3" json:"dish_id,omitempty"`
	Stuempno             string   `protobuf:"bytes,2,opt,name=stuempno,proto3" json:"stuempno,omitempty"`
	Cardno               int32    `protobuf:"varint,3,opt,name=cardno,proto3" json:"cardno,omitempty"`
	Cardphyid            string   `protobuf:"bytes,4,opt,name=cardphyid,proto3" json:"cardphyid,omitempty"`
	Feerate              int32    `protobuf:"varint,5,opt,name=feerate,proto3" json:"feerate,omitempty"`
	AccountBala          int32    `protobuf:"varint,6,opt,name=account_bala,json=accountBala,proto3" json:"account_bala,omitempty"`
	Offline              bool     `protobuf:"varint,7,opt,name=offline,proto3" json:"offline,omitempty"`
	Custname             string   `protobuf:"bytes,8,opt,name=custname,proto3" json:"custname,omitempty"`
	Source               string   `protobuf:"bytes,9,opt,name=source,proto3" json:"source,omitempty"`
	ExpireDate           string   `protobuf:"bytes,10,opt,name=expire_date,json=expireDate,proto3" json:"expire_date,omitempty"`
	Seqno                string   `protobuf:"bytes,11,opt,name=seqno,proto3" json:"seqno,omitempty"`
	Termid               string   `protobuf:"bytes,12,opt,name=termid,proto3" json:"termid,omitempty"`
	Paymode              string   `protobuf:"bytes,13,opt,name=paymode,proto3" json:"paymode,omitempty"`
	Refno                string   `protobuf:"bytes,14,opt,name=refno,proto3" json:"refno,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BindDishRequest) Reset()         { *m = BindDishRequest{} }
func (m *BindDishRequest) String() string { return proto.CompactTextString(m) }
func (*BindDishRequest) ProtoMessage()    {}
func (*BindDishRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{5}
}

func (m *BindDishRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BindDishRequest.Unmarshal(m, b)
}
func (m *BindDishRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BindDishRequest.Marshal(b, m, deterministic)
}
func (m *BindDishRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BindDishRequest.Merge(m, src)
}
func (m *BindDishRequest) XXX_Size() int {
	return xxx_messageInfo_BindDishRequest.Size(m)
}
func (m *BindDishRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BindDishRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BindDishRequest proto.InternalMessageInfo

func (m *BindDishRequest) GetDishId() string {
	if m != nil {
		return m.DishId
	}
	return ""
}

func (m *BindDishRequest) GetStuempno() string {
	if m != nil {
		return m.Stuempno
	}
	return ""
}

func (m *BindDishRequest) GetCardno() int32 {
	if m != nil {
		return m.Cardno
	}
	return 0
}

func (m *BindDishRequest) GetCardphyid() string {
	if m != nil {
		return m.Cardphyid
	}
	return ""
}

func (m *BindDishRequest) GetFeerate() int32 {
	if m != nil {
		return m.Feerate
	}
	return 0
}

func (m *BindDishRequest) GetAccountBala() int32 {
	if m != nil {
		return m.AccountBala
	}
	return 0
}

func (m *BindDishRequest) GetOffline() bool {
	if m != nil {
		return m.Offline
	}
	return false
}

func (m *BindDishRequest) GetCustname() string {
	if m != nil {
		return m.Custname
	}
	return ""
}

func (m *BindDishRequest) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

func (m *BindDishRequest) GetExpireDate() string {
	if m != nil {
		return m.ExpireDate
	}
	return ""
}

func (m *BindDishRequest) GetSeqno() string {
	if m != nil {
		return m.Seqno
	}
	return ""
}

func (m *BindDishRequest) GetTermid() string {
	if m != nil {
		return m.Termid
	}
	return ""
}

func (m *BindDishRequest) GetPaymode() string {
	if m != nil {
		return m.Paymode
	}
	return ""
}

func (m *BindDishRequest) GetRefno() string {
	if m != nil {
		return m.Refno
	}
	return ""
}

// 绑定餐盘应答
type BindDishResponse struct {
	Billno               string         `protobuf:"bytes,1,opt,name=billno,proto3" json:"billno,omitempty"`
	BindStatus           DishBindStatus `protobuf:"varint,2,opt,name=bindStatus,proto3,enum=DishBindStatus" json:"bindStatus,omitempty"`
	Stuempno             string         `protobuf:"bytes,3,opt,name=stuempno,proto3" json:"stuempno,omitempty"`
	Cardno               int32          `protobuf:"varint,4,opt,name=cardno,proto3" json:"cardno,omitempty"`
	Cardphyid            string         `protobuf:"bytes,5,opt,name=cardphyid,proto3" json:"cardphyid,omitempty"`
	Custname             string         `protobuf:"bytes,6,opt,name=custname,proto3" json:"custname,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *BindDishResponse) Reset()         { *m = BindDishResponse{} }
func (m *BindDishResponse) String() string { return proto.CompactTextString(m) }
func (*BindDishResponse) ProtoMessage()    {}
func (*BindDishResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{6}
}

func (m *BindDishResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BindDishResponse.Unmarshal(m, b)
}
func (m *BindDishResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BindDishResponse.Marshal(b, m, deterministic)
}
func (m *BindDishResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BindDishResponse.Merge(m, src)
}
func (m *BindDishResponse) XXX_Size() int {
	return xxx_messageInfo_BindDishResponse.Size(m)
}
func (m *BindDishResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BindDishResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BindDishResponse proto.InternalMessageInfo

func (m *BindDishResponse) GetBillno() string {
	if m != nil {
		return m.Billno
	}
	return ""
}

func (m *BindDishResponse) GetBindStatus() DishBindStatus {
	if m != nil {
		return m.BindStatus
	}
	return DishBindStatus_NEW
}

func (m *BindDishResponse) GetStuempno() string {
	if m != nil {
		return m.Stuempno
	}
	return ""
}

func (m *BindDishResponse) GetCardno() int32 {
	if m != nil {
		return m.Cardno
	}
	return 0
}

func (m *BindDishResponse) GetCardphyid() string {
	if m != nil {
		return m.Cardphyid
	}
	return ""
}

func (m *BindDishResponse) GetCustname() string {
	if m != nil {
		return m.Custname
	}
	return ""
}

// 解绑餐盘请求
type UnbindDishRequest struct {
	DishId               string   `protobuf:"bytes,1,opt,name=dish_id,json=dishId,proto3" json:"dish_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnbindDishRequest) Reset()         { *m = UnbindDishRequest{} }
func (m *UnbindDishRequest) String() string { return proto.CompactTextString(m) }
func (*UnbindDishRequest) ProtoMessage()    {}
func (*UnbindDishRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{7}
}

func (m *UnbindDishRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnbindDishRequest.Unmarshal(m, b)
}
func (m *UnbindDishRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnbindDishRequest.Marshal(b, m, deterministic)
}
func (m *UnbindDishRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnbindDishRequest.Merge(m, src)
}
func (m *UnbindDishRequest) XXX_Size() int {
	return xxx_messageInfo_UnbindDishRequest.Size(m)
}
func (m *UnbindDishRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UnbindDishRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UnbindDishRequest proto.InternalMessageInfo

func (m *UnbindDishRequest) GetDishId() string {
	if m != nil {
		return m.DishId
	}
	return ""
}

// 解绑餐盘应答
type UnbindDishResponse struct {
	Billno               string   `protobuf:"bytes,1,opt,name=billno,proto3" json:"billno,omitempty"`
	Stuempno             string   `protobuf:"bytes,2,opt,name=stuempno,proto3" json:"stuempno,omitempty"`
	Custname             string   `protobuf:"bytes,3,opt,name=custname,proto3" json:"custname,omitempty"`
	Amount               int32    `protobuf:"varint,4,opt,name=amount,proto3" json:"amount,omitempty"`
	FreeBalance          int32    `protobuf:"varint,5,opt,name=free_balance,json=freeBalance,proto3" json:"free_balance,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnbindDishResponse) Reset()         { *m = UnbindDishResponse{} }
func (m *UnbindDishResponse) String() string { return proto.CompactTextString(m) }
func (*UnbindDishResponse) ProtoMessage()    {}
func (*UnbindDishResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{8}
}

func (m *UnbindDishResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnbindDishResponse.Unmarshal(m, b)
}
func (m *UnbindDishResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnbindDishResponse.Marshal(b, m, deterministic)
}
func (m *UnbindDishResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnbindDishResponse.Merge(m, src)
}
func (m *UnbindDishResponse) XXX_Size() int {
	return xxx_messageInfo_UnbindDishResponse.Size(m)
}
func (m *UnbindDishResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UnbindDishResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UnbindDishResponse proto.InternalMessageInfo

func (m *UnbindDishResponse) GetBillno() string {
	if m != nil {
		return m.Billno
	}
	return ""
}

func (m *UnbindDishResponse) GetStuempno() string {
	if m != nil {
		return m.Stuempno
	}
	return ""
}

func (m *UnbindDishResponse) GetCustname() string {
	if m != nil {
		return m.Custname
	}
	return ""
}

func (m *UnbindDishResponse) GetAmount() int32 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *UnbindDishResponse) GetFreeBalance() int32 {
	if m != nil {
		return m.FreeBalance
	}
	return 0
}

// 查询托盘订单
type DishQueryRequest struct {
	DishId               string   `protobuf:"bytes,1,opt,name=dish_id,json=dishId,proto3" json:"dish_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DishQueryRequest) Reset()         { *m = DishQueryRequest{} }
func (m *DishQueryRequest) String() string { return proto.CompactTextString(m) }
func (*DishQueryRequest) ProtoMessage()    {}
func (*DishQueryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{9}
}

func (m *DishQueryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DishQueryRequest.Unmarshal(m, b)
}
func (m *DishQueryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DishQueryRequest.Marshal(b, m, deterministic)
}
func (m *DishQueryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DishQueryRequest.Merge(m, src)
}
func (m *DishQueryRequest) XXX_Size() int {
	return xxx_messageInfo_DishQueryRequest.Size(m)
}
func (m *DishQueryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DishQueryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DishQueryRequest proto.InternalMessageInfo

func (m *DishQueryRequest) GetDishId() string {
	if m != nil {
		return m.DishId
	}
	return ""
}

// 查询托盘订单结果
type DishQueryResponse struct {
	Billno               string             `protobuf:"bytes,1,opt,name=billno,proto3" json:"billno,omitempty"`
	Stuempno             string             `protobuf:"bytes,2,opt,name=stuempno,proto3" json:"stuempno,omitempty"`
	Custname             string             `protobuf:"bytes,3,opt,name=custname,proto3" json:"custname,omitempty"`
	Amount               int32              `protobuf:"varint,4,opt,name=amount,proto3" json:"amount,omitempty"`
	Balance              int32              `protobuf:"varint,5,opt,name=balance,proto3" json:"balance,omitempty"`
	Status               string             `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	Paymode              string             `protobuf:"bytes,7,opt,name=paymode,proto3" json:"paymode,omitempty"`
	Details              []*DishTransDetail `protobuf:"bytes,8,rep,name=details,proto3" json:"details,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *DishQueryResponse) Reset()         { *m = DishQueryResponse{} }
func (m *DishQueryResponse) String() string { return proto.CompactTextString(m) }
func (*DishQueryResponse) ProtoMessage()    {}
func (*DishQueryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{10}
}

func (m *DishQueryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DishQueryResponse.Unmarshal(m, b)
}
func (m *DishQueryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DishQueryResponse.Marshal(b, m, deterministic)
}
func (m *DishQueryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DishQueryResponse.Merge(m, src)
}
func (m *DishQueryResponse) XXX_Size() int {
	return xxx_messageInfo_DishQueryResponse.Size(m)
}
func (m *DishQueryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DishQueryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DishQueryResponse proto.InternalMessageInfo

func (m *DishQueryResponse) GetBillno() string {
	if m != nil {
		return m.Billno
	}
	return ""
}

func (m *DishQueryResponse) GetStuempno() string {
	if m != nil {
		return m.Stuempno
	}
	return ""
}

func (m *DishQueryResponse) GetCustname() string {
	if m != nil {
		return m.Custname
	}
	return ""
}

func (m *DishQueryResponse) GetAmount() int32 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *DishQueryResponse) GetBalance() int32 {
	if m != nil {
		return m.Balance
	}
	return 0
}

func (m *DishQueryResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *DishQueryResponse) GetPaymode() string {
	if m != nil {
		return m.Paymode
	}
	return ""
}

func (m *DishQueryResponse) GetDetails() []*DishTransDetail {
	if m != nil {
		return m.Details
	}
	return nil
}

// 订单确认请求
type TransConfirmRequest struct {
	DishId               string   `protobuf:"bytes,1,opt,name=dish_id,json=dishId,proto3" json:"dish_id,omitempty"`
	Billno               string   `protobuf:"bytes,2,opt,name=billno,proto3" json:"billno,omitempty"`
	PayAmount            int32    `protobuf:"varint,3,opt,name=pay_amount,json=payAmount,proto3" json:"pay_amount,omitempty"`
	ExternalRefno        string   `protobuf:"bytes,4,opt,name=external_refno,json=externalRefno,proto3" json:"external_refno,omitempty"`
	PayDate              string   `protobuf:"bytes,5,opt,name=pay_date,json=payDate,proto3" json:"pay_date,omitempty"`
	PayTime              string   `protobuf:"bytes,6,opt,name=pay_time,json=payTime,proto3" json:"pay_time,omitempty"`
	PaySource            string   `protobuf:"bytes,7,opt,name=pay_source,json=paySource,proto3" json:"pay_source,omitempty"`
	Remark               string   `protobuf:"bytes,8,opt,name=remark,proto3" json:"remark,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TransConfirmRequest) Reset()         { *m = TransConfirmRequest{} }
func (m *TransConfirmRequest) String() string { return proto.CompactTextString(m) }
func (*TransConfirmRequest) ProtoMessage()    {}
func (*TransConfirmRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{11}
}

func (m *TransConfirmRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransConfirmRequest.Unmarshal(m, b)
}
func (m *TransConfirmRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransConfirmRequest.Marshal(b, m, deterministic)
}
func (m *TransConfirmRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransConfirmRequest.Merge(m, src)
}
func (m *TransConfirmRequest) XXX_Size() int {
	return xxx_messageInfo_TransConfirmRequest.Size(m)
}
func (m *TransConfirmRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TransConfirmRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TransConfirmRequest proto.InternalMessageInfo

func (m *TransConfirmRequest) GetDishId() string {
	if m != nil {
		return m.DishId
	}
	return ""
}

func (m *TransConfirmRequest) GetBillno() string {
	if m != nil {
		return m.Billno
	}
	return ""
}

func (m *TransConfirmRequest) GetPayAmount() int32 {
	if m != nil {
		return m.PayAmount
	}
	return 0
}

func (m *TransConfirmRequest) GetExternalRefno() string {
	if m != nil {
		return m.ExternalRefno
	}
	return ""
}

func (m *TransConfirmRequest) GetPayDate() string {
	if m != nil {
		return m.PayDate
	}
	return ""
}

func (m *TransConfirmRequest) GetPayTime() string {
	if m != nil {
		return m.PayTime
	}
	return ""
}

func (m *TransConfirmRequest) GetPaySource() string {
	if m != nil {
		return m.PaySource
	}
	return ""
}

func (m *TransConfirmRequest) GetRemark() string {
	if m != nil {
		return m.Remark
	}
	return ""
}

// 订单确认请求应答
type TransConfirmResponse struct {
	Billno               string   `protobuf:"bytes,1,opt,name=billno,proto3" json:"billno,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TransConfirmResponse) Reset()         { *m = TransConfirmResponse{} }
func (m *TransConfirmResponse) String() string { return proto.CompactTextString(m) }
func (*TransConfirmResponse) ProtoMessage()    {}
func (*TransConfirmResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{12}
}

func (m *TransConfirmResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransConfirmResponse.Unmarshal(m, b)
}
func (m *TransConfirmResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransConfirmResponse.Marshal(b, m, deterministic)
}
func (m *TransConfirmResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransConfirmResponse.Merge(m, src)
}
func (m *TransConfirmResponse) XXX_Size() int {
	return xxx_messageInfo_TransConfirmResponse.Size(m)
}
func (m *TransConfirmResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TransConfirmResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TransConfirmResponse proto.InternalMessageInfo

func (m *TransConfirmResponse) GetBillno() string {
	if m != nil {
		return m.Billno
	}
	return ""
}

// 餐盘初始化请求
type InitDishRequest struct {
	AccessKey            string   `protobuf:"bytes,1,opt,name=access_key,json=accessKey,proto3" json:"access_key,omitempty"`
	DishId               string   `protobuf:"bytes,3,opt,name=dish_id,json=dishId,proto3" json:"dish_id,omitempty"`
	FoodId               string   `protobuf:"bytes,4,opt,name=food_id,json=foodId,proto3" json:"food_id,omitempty"`
	FoodWeight           int32    `protobuf:"varint,5,opt,name=food_weight,json=foodWeight,proto3" json:"food_weight,omitempty"`
	ForceQuery           bool     `protobuf:"varint,6,opt,name=force_query,json=forceQuery,proto3" json:"force_query,omitempty"`
	Termno               string   `protobuf:"bytes,7,opt,name=termno,proto3" json:"termno,omitempty"`
	Termid               string   `protobuf:"bytes,8,opt,name=termid,proto3" json:"termid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InitDishRequest) Reset()         { *m = InitDishRequest{} }
func (m *InitDishRequest) String() string { return proto.CompactTextString(m) }
func (*InitDishRequest) ProtoMessage()    {}
func (*InitDishRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{13}
}

func (m *InitDishRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InitDishRequest.Unmarshal(m, b)
}
func (m *InitDishRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InitDishRequest.Marshal(b, m, deterministic)
}
func (m *InitDishRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InitDishRequest.Merge(m, src)
}
func (m *InitDishRequest) XXX_Size() int {
	return xxx_messageInfo_InitDishRequest.Size(m)
}
func (m *InitDishRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InitDishRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InitDishRequest proto.InternalMessageInfo

func (m *InitDishRequest) GetAccessKey() string {
	if m != nil {
		return m.AccessKey
	}
	return ""
}

func (m *InitDishRequest) GetDishId() string {
	if m != nil {
		return m.DishId
	}
	return ""
}

func (m *InitDishRequest) GetFoodId() string {
	if m != nil {
		return m.FoodId
	}
	return ""
}

func (m *InitDishRequest) GetFoodWeight() int32 {
	if m != nil {
		return m.FoodWeight
	}
	return 0
}

func (m *InitDishRequest) GetForceQuery() bool {
	if m != nil {
		return m.ForceQuery
	}
	return false
}

func (m *InitDishRequest) GetTermno() string {
	if m != nil {
		return m.Termno
	}
	return ""
}

func (m *InitDishRequest) GetTermid() string {
	if m != nil {
		return m.Termid
	}
	return ""
}

// 餐盘初始化应答
type InitDishResponse struct {
	Stuempno             string   `protobuf:"bytes,1,opt,name=stuempno,proto3" json:"stuempno,omitempty"`
	Custname             string   `protobuf:"bytes,2,opt,name=custname,proto3" json:"custname,omitempty"`
	AccountBala          int32    `protobuf:"varint,3,opt,name=account_bala,json=accountBala,proto3" json:"account_bala,omitempty"`
	Amount               int32    `protobuf:"varint,4,opt,name=amount,proto3" json:"amount,omitempty"`
	Feerate              int32    `protobuf:"varint,5,opt,name=feerate,proto3" json:"feerate,omitempty"`
	Message              string   `protobuf:"bytes,6,opt,name=message,proto3" json:"message,omitempty"`
	Offline              bool     `protobuf:"varint,7,opt,name=offline,proto3" json:"offline,omitempty"`
	Billno               string   `protobuf:"bytes,8,opt,name=billno,proto3" json:"billno,omitempty"`
	ExpireMinutes        int32    `protobuf:"varint,9,opt,name=expire_minutes,json=expireMinutes,proto3" json:"expire_minutes,omitempty"`
	Paymode              string   `protobuf:"bytes,10,opt,name=paymode,proto3" json:"paymode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InitDishResponse) Reset()         { *m = InitDishResponse{} }
func (m *InitDishResponse) String() string { return proto.CompactTextString(m) }
func (*InitDishResponse) ProtoMessage()    {}
func (*InitDishResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{14}
}

func (m *InitDishResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InitDishResponse.Unmarshal(m, b)
}
func (m *InitDishResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InitDishResponse.Marshal(b, m, deterministic)
}
func (m *InitDishResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InitDishResponse.Merge(m, src)
}
func (m *InitDishResponse) XXX_Size() int {
	return xxx_messageInfo_InitDishResponse.Size(m)
}
func (m *InitDishResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_InitDishResponse.DiscardUnknown(m)
}

var xxx_messageInfo_InitDishResponse proto.InternalMessageInfo

func (m *InitDishResponse) GetStuempno() string {
	if m != nil {
		return m.Stuempno
	}
	return ""
}

func (m *InitDishResponse) GetCustname() string {
	if m != nil {
		return m.Custname
	}
	return ""
}

func (m *InitDishResponse) GetAccountBala() int32 {
	if m != nil {
		return m.AccountBala
	}
	return 0
}

func (m *InitDishResponse) GetAmount() int32 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *InitDishResponse) GetFeerate() int32 {
	if m != nil {
		return m.Feerate
	}
	return 0
}

func (m *InitDishResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *InitDishResponse) GetOffline() bool {
	if m != nil {
		return m.Offline
	}
	return false
}

func (m *InitDishResponse) GetBillno() string {
	if m != nil {
		return m.Billno
	}
	return ""
}

func (m *InitDishResponse) GetExpireMinutes() int32 {
	if m != nil {
		return m.ExpireMinutes
	}
	return 0
}

func (m *InitDishResponse) GetPaymode() string {
	if m != nil {
		return m.Paymode
	}
	return ""
}

// 餐盘消费确认请求
type ConfirmDishRequest struct {
	AccessKey            string   `protobuf:"bytes,1,opt,name=access_key,json=accessKey,proto3" json:"access_key,omitempty"`
	Price                int32    `protobuf:"varint,2,opt,name=price,proto3" json:"price,omitempty"`
	DishId               string   `protobuf:"bytes,3,opt,name=dish_id,json=dishId,proto3" json:"dish_id,omitempty"`
	FoodId               string   `protobuf:"bytes,4,opt,name=food_id,json=foodId,proto3" json:"food_id,omitempty"`
	BuyWeight            int32    `protobuf:"varint,5,opt,name=buy_weight,json=buyWeight,proto3" json:"buy_weight,omitempty"`
	Amount               int32    `protobuf:"varint,6,opt,name=amount,proto3" json:"amount,omitempty"`
	Billno               string   `protobuf:"bytes,7,opt,name=billno,proto3" json:"billno,omitempty"`
	Unit                 int32    `protobuf:"varint,8,opt,name=unit,proto3" json:"unit,omitempty"`
	DeviceSeqno          string   `protobuf:"bytes,9,opt,name=device_seqno,json=deviceSeqno,proto3" json:"device_seqno,omitempty"`
	FoodName             string   `protobuf:"bytes,10,opt,name=food_name,json=foodName,proto3" json:"food_name,omitempty"`
	Termno               string   `protobuf:"bytes,11,opt,name=termno,proto3" json:"termno,omitempty"`
	BuyNum               int32    `protobuf:"varint,12,opt,name=buy_num,json=buyNum,proto3" json:"buy_num,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConfirmDishRequest) Reset()         { *m = ConfirmDishRequest{} }
func (m *ConfirmDishRequest) String() string { return proto.CompactTextString(m) }
func (*ConfirmDishRequest) ProtoMessage()    {}
func (*ConfirmDishRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{15}
}

func (m *ConfirmDishRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfirmDishRequest.Unmarshal(m, b)
}
func (m *ConfirmDishRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfirmDishRequest.Marshal(b, m, deterministic)
}
func (m *ConfirmDishRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfirmDishRequest.Merge(m, src)
}
func (m *ConfirmDishRequest) XXX_Size() int {
	return xxx_messageInfo_ConfirmDishRequest.Size(m)
}
func (m *ConfirmDishRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfirmDishRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ConfirmDishRequest proto.InternalMessageInfo

func (m *ConfirmDishRequest) GetAccessKey() string {
	if m != nil {
		return m.AccessKey
	}
	return ""
}

func (m *ConfirmDishRequest) GetPrice() int32 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *ConfirmDishRequest) GetDishId() string {
	if m != nil {
		return m.DishId
	}
	return ""
}

func (m *ConfirmDishRequest) GetFoodId() string {
	if m != nil {
		return m.FoodId
	}
	return ""
}

func (m *ConfirmDishRequest) GetBuyWeight() int32 {
	if m != nil {
		return m.BuyWeight
	}
	return 0
}

func (m *ConfirmDishRequest) GetAmount() int32 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *ConfirmDishRequest) GetBillno() string {
	if m != nil {
		return m.Billno
	}
	return ""
}

func (m *ConfirmDishRequest) GetUnit() int32 {
	if m != nil {
		return m.Unit
	}
	return 0
}

func (m *ConfirmDishRequest) GetDeviceSeqno() string {
	if m != nil {
		return m.DeviceSeqno
	}
	return ""
}

func (m *ConfirmDishRequest) GetFoodName() string {
	if m != nil {
		return m.FoodName
	}
	return ""
}

func (m *ConfirmDishRequest) GetTermno() string {
	if m != nil {
		return m.Termno
	}
	return ""
}

func (m *ConfirmDishRequest) GetBuyNum() int32 {
	if m != nil {
		return m.BuyNum
	}
	return 0
}

// 菜品消费明细
type DishTransDetail struct {
	FoodId               string   `protobuf:"bytes,1,opt,name=food_id,json=foodId,proto3" json:"food_id,omitempty"`
	FoodName             string   `protobuf:"bytes,2,opt,name=food_name,json=foodName,proto3" json:"food_name,omitempty"`
	Amount               int32    `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Weight               int32    `protobuf:"varint,4,opt,name=weight,proto3" json:"weight,omitempty"`
	Price                int32    `protobuf:"varint,5,opt,name=price,proto3" json:"price,omitempty"`
	Unit                 int32    `protobuf:"varint,6,opt,name=unit,proto3" json:"unit,omitempty"`
	Qty                  int32    `protobuf:"varint,7,opt,name=qty,proto3" json:"qty,omitempty"`
	Termno               string   `protobuf:"bytes,8,opt,name=termno,proto3" json:"termno,omitempty"`
	DeviceSeqno          string   `protobuf:"bytes,9,opt,name=device_seqno,json=deviceSeqno,proto3" json:"device_seqno,omitempty"`
	Flag                 string   `protobuf:"bytes,10,opt,name=flag,proto3" json:"flag,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DishTransDetail) Reset()         { *m = DishTransDetail{} }
func (m *DishTransDetail) String() string { return proto.CompactTextString(m) }
func (*DishTransDetail) ProtoMessage()    {}
func (*DishTransDetail) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{16}
}

func (m *DishTransDetail) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DishTransDetail.Unmarshal(m, b)
}
func (m *DishTransDetail) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DishTransDetail.Marshal(b, m, deterministic)
}
func (m *DishTransDetail) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DishTransDetail.Merge(m, src)
}
func (m *DishTransDetail) XXX_Size() int {
	return xxx_messageInfo_DishTransDetail.Size(m)
}
func (m *DishTransDetail) XXX_DiscardUnknown() {
	xxx_messageInfo_DishTransDetail.DiscardUnknown(m)
}

var xxx_messageInfo_DishTransDetail proto.InternalMessageInfo

func (m *DishTransDetail) GetFoodId() string {
	if m != nil {
		return m.FoodId
	}
	return ""
}

func (m *DishTransDetail) GetFoodName() string {
	if m != nil {
		return m.FoodName
	}
	return ""
}

func (m *DishTransDetail) GetAmount() int32 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *DishTransDetail) GetWeight() int32 {
	if m != nil {
		return m.Weight
	}
	return 0
}

func (m *DishTransDetail) GetPrice() int32 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *DishTransDetail) GetUnit() int32 {
	if m != nil {
		return m.Unit
	}
	return 0
}

func (m *DishTransDetail) GetQty() int32 {
	if m != nil {
		return m.Qty
	}
	return 0
}

func (m *DishTransDetail) GetTermno() string {
	if m != nil {
		return m.Termno
	}
	return ""
}

func (m *DishTransDetail) GetDeviceSeqno() string {
	if m != nil {
		return m.DeviceSeqno
	}
	return ""
}

func (m *DishTransDetail) GetFlag() string {
	if m != nil {
		return m.Flag
	}
	return ""
}

// 餐盘消费确认应答
type ConfirmDishResponse struct {
	Result               string             `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	Message              string             `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	AccountBala          int32              `protobuf:"varint,3,opt,name=account_bala,json=accountBala,proto3" json:"account_bala,omitempty"`
	Details              []*DishTransDetail `protobuf:"bytes,4,rep,name=details,proto3" json:"details,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *ConfirmDishResponse) Reset()         { *m = ConfirmDishResponse{} }
func (m *ConfirmDishResponse) String() string { return proto.CompactTextString(m) }
func (*ConfirmDishResponse) ProtoMessage()    {}
func (*ConfirmDishResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{17}
}

func (m *ConfirmDishResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfirmDishResponse.Unmarshal(m, b)
}
func (m *ConfirmDishResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfirmDishResponse.Marshal(b, m, deterministic)
}
func (m *ConfirmDishResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfirmDishResponse.Merge(m, src)
}
func (m *ConfirmDishResponse) XXX_Size() int {
	return xxx_messageInfo_ConfirmDishResponse.Size(m)
}
func (m *ConfirmDishResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfirmDishResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ConfirmDishResponse proto.InternalMessageInfo

func (m *ConfirmDishResponse) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

func (m *ConfirmDishResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *ConfirmDishResponse) GetAccountBala() int32 {
	if m != nil {
		return m.AccountBala
	}
	return 0
}

func (m *ConfirmDishResponse) GetDetails() []*DishTransDetail {
	if m != nil {
		return m.Details
	}
	return nil
}

type WeighingScaleEvent struct {
	AccessKey            string              `protobuf:"bytes,1,opt,name=access_key,json=accessKey,proto3" json:"access_key,omitempty"`
	Event                string              `protobuf:"bytes,2,opt,name=event,proto3" json:"event,omitempty"`
	Message              string              `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Status               WeighingScaleStatus `protobuf:"varint,4,opt,name=status,proto3,enum=WeighingScaleStatus" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *WeighingScaleEvent) Reset()         { *m = WeighingScaleEvent{} }
func (m *WeighingScaleEvent) String() string { return proto.CompactTextString(m) }
func (*WeighingScaleEvent) ProtoMessage()    {}
func (*WeighingScaleEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{18}
}

func (m *WeighingScaleEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WeighingScaleEvent.Unmarshal(m, b)
}
func (m *WeighingScaleEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WeighingScaleEvent.Marshal(b, m, deterministic)
}
func (m *WeighingScaleEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WeighingScaleEvent.Merge(m, src)
}
func (m *WeighingScaleEvent) XXX_Size() int {
	return xxx_messageInfo_WeighingScaleEvent.Size(m)
}
func (m *WeighingScaleEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_WeighingScaleEvent.DiscardUnknown(m)
}

var xxx_messageInfo_WeighingScaleEvent proto.InternalMessageInfo

func (m *WeighingScaleEvent) GetAccessKey() string {
	if m != nil {
		return m.AccessKey
	}
	return ""
}

func (m *WeighingScaleEvent) GetEvent() string {
	if m != nil {
		return m.Event
	}
	return ""
}

func (m *WeighingScaleEvent) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *WeighingScaleEvent) GetStatus() WeighingScaleStatus {
	if m != nil {
		return m.Status
	}
	return WeighingScaleStatus_OFFLINE
}

// 菜品下载请求
type DownloadFoodRequest struct {
	AccessKey            string   `protobuf:"bytes,1,opt,name=access_key,json=accessKey,proto3" json:"access_key,omitempty"`
	FoodVerno            string   `protobuf:"bytes,2,opt,name=food_verno,json=foodVerno,proto3" json:"food_verno,omitempty"`
	Termno               string   `protobuf:"bytes,3,opt,name=termno,proto3" json:"termno,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DownloadFoodRequest) Reset()         { *m = DownloadFoodRequest{} }
func (m *DownloadFoodRequest) String() string { return proto.CompactTextString(m) }
func (*DownloadFoodRequest) ProtoMessage()    {}
func (*DownloadFoodRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{19}
}

func (m *DownloadFoodRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DownloadFoodRequest.Unmarshal(m, b)
}
func (m *DownloadFoodRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DownloadFoodRequest.Marshal(b, m, deterministic)
}
func (m *DownloadFoodRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DownloadFoodRequest.Merge(m, src)
}
func (m *DownloadFoodRequest) XXX_Size() int {
	return xxx_messageInfo_DownloadFoodRequest.Size(m)
}
func (m *DownloadFoodRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DownloadFoodRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DownloadFoodRequest proto.InternalMessageInfo

func (m *DownloadFoodRequest) GetAccessKey() string {
	if m != nil {
		return m.AccessKey
	}
	return ""
}

func (m *DownloadFoodRequest) GetFoodVerno() string {
	if m != nil {
		return m.FoodVerno
	}
	return ""
}

func (m *DownloadFoodRequest) GetTermno() string {
	if m != nil {
		return m.Termno
	}
	return ""
}

// 菜品下载信息应答
type FoodResponse struct {
	FoodVerno            string   `protobuf:"bytes,1,opt,name=food_verno,json=foodVerno,proto3" json:"food_verno,omitempty"`
	Retjson              string   `protobuf:"bytes,2,opt,name=retjson,proto3" json:"retjson,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FoodResponse) Reset()         { *m = FoodResponse{} }
func (m *FoodResponse) String() string { return proto.CompactTextString(m) }
func (*FoodResponse) ProtoMessage()    {}
func (*FoodResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{20}
}

func (m *FoodResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FoodResponse.Unmarshal(m, b)
}
func (m *FoodResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FoodResponse.Marshal(b, m, deterministic)
}
func (m *FoodResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FoodResponse.Merge(m, src)
}
func (m *FoodResponse) XXX_Size() int {
	return xxx_messageInfo_FoodResponse.Size(m)
}
func (m *FoodResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FoodResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FoodResponse proto.InternalMessageInfo

func (m *FoodResponse) GetFoodVerno() string {
	if m != nil {
		return m.FoodVerno
	}
	return ""
}

func (m *FoodResponse) GetRetjson() string {
	if m != nil {
		return m.Retjson
	}
	return ""
}

// 餐次下载请求
type DownloadMealRequest struct {
	AccessKey            string   `protobuf:"bytes,1,opt,name=access_key,json=accessKey,proto3" json:"access_key,omitempty"`
	Termno               string   `protobuf:"bytes,2,opt,name=termno,proto3" json:"termno,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DownloadMealRequest) Reset()         { *m = DownloadMealRequest{} }
func (m *DownloadMealRequest) String() string { return proto.CompactTextString(m) }
func (*DownloadMealRequest) ProtoMessage()    {}
func (*DownloadMealRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{21}
}

func (m *DownloadMealRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DownloadMealRequest.Unmarshal(m, b)
}
func (m *DownloadMealRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DownloadMealRequest.Marshal(b, m, deterministic)
}
func (m *DownloadMealRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DownloadMealRequest.Merge(m, src)
}
func (m *DownloadMealRequest) XXX_Size() int {
	return xxx_messageInfo_DownloadMealRequest.Size(m)
}
func (m *DownloadMealRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DownloadMealRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DownloadMealRequest proto.InternalMessageInfo

func (m *DownloadMealRequest) GetAccessKey() string {
	if m != nil {
		return m.AccessKey
	}
	return ""
}

func (m *DownloadMealRequest) GetTermno() string {
	if m != nil {
		return m.Termno
	}
	return ""
}

// 餐次应答
type MealResponse struct {
	Retjson              string   `protobuf:"bytes,1,opt,name=retjson,proto3" json:"retjson,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MealResponse) Reset()         { *m = MealResponse{} }
func (m *MealResponse) String() string { return proto.CompactTextString(m) }
func (*MealResponse) ProtoMessage()    {}
func (*MealResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{22}
}

func (m *MealResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MealResponse.Unmarshal(m, b)
}
func (m *MealResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MealResponse.Marshal(b, m, deterministic)
}
func (m *MealResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MealResponse.Merge(m, src)
}
func (m *MealResponse) XXX_Size() int {
	return xxx_messageInfo_MealResponse.Size(m)
}
func (m *MealResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MealResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MealResponse proto.InternalMessageInfo

func (m *MealResponse) GetRetjson() string {
	if m != nil {
		return m.Retjson
	}
	return ""
}

// 参数下载
type DownloadSysParaRequest struct {
	AccessKey            string   `protobuf:"bytes,1,opt,name=access_key,json=accessKey,proto3" json:"access_key,omitempty"`
	Termno               string   `protobuf:"bytes,2,opt,name=termno,proto3" json:"termno,omitempty"`
	ParaVerNo            int32    `protobuf:"varint,3,opt,name=para_ver_no,json=paraVerNo,proto3" json:"para_ver_no,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DownloadSysParaRequest) Reset()         { *m = DownloadSysParaRequest{} }
func (m *DownloadSysParaRequest) String() string { return proto.CompactTextString(m) }
func (*DownloadSysParaRequest) ProtoMessage()    {}
func (*DownloadSysParaRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{23}
}

func (m *DownloadSysParaRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DownloadSysParaRequest.Unmarshal(m, b)
}
func (m *DownloadSysParaRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DownloadSysParaRequest.Marshal(b, m, deterministic)
}
func (m *DownloadSysParaRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DownloadSysParaRequest.Merge(m, src)
}
func (m *DownloadSysParaRequest) XXX_Size() int {
	return xxx_messageInfo_DownloadSysParaRequest.Size(m)
}
func (m *DownloadSysParaRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DownloadSysParaRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DownloadSysParaRequest proto.InternalMessageInfo

func (m *DownloadSysParaRequest) GetAccessKey() string {
	if m != nil {
		return m.AccessKey
	}
	return ""
}

func (m *DownloadSysParaRequest) GetTermno() string {
	if m != nil {
		return m.Termno
	}
	return ""
}

func (m *DownloadSysParaRequest) GetParaVerNo() int32 {
	if m != nil {
		return m.ParaVerNo
	}
	return 0
}

type SysparaResponse struct {
	ParaVerNo            int32    `protobuf:"varint,1,opt,name=para_ver_no,json=paraVerNo,proto3" json:"para_ver_no,omitempty"`
	Retjson              string   `protobuf:"bytes,2,opt,name=retjson,proto3" json:"retjson,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SysparaResponse) Reset()         { *m = SysparaResponse{} }
func (m *SysparaResponse) String() string { return proto.CompactTextString(m) }
func (*SysparaResponse) ProtoMessage()    {}
func (*SysparaResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{24}
}

func (m *SysparaResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SysparaResponse.Unmarshal(m, b)
}
func (m *SysparaResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SysparaResponse.Marshal(b, m, deterministic)
}
func (m *SysparaResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SysparaResponse.Merge(m, src)
}
func (m *SysparaResponse) XXX_Size() int {
	return xxx_messageInfo_SysparaResponse.Size(m)
}
func (m *SysparaResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SysparaResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SysparaResponse proto.InternalMessageInfo

func (m *SysparaResponse) GetParaVerNo() int32 {
	if m != nil {
		return m.ParaVerNo
	}
	return 0
}

func (m *SysparaResponse) GetRetjson() string {
	if m != nil {
		return m.Retjson
	}
	return ""
}

// 餐台操作信息上传
type WeighActionRequest struct {
	AccessKey            string   `protobuf:"bytes,1,opt,name=access_key,json=accessKey,proto3" json:"access_key,omitempty"`
	Termno               string   `protobuf:"bytes,2,opt,name=termno,proto3" json:"termno,omitempty"`
	Action               string   `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty"`
	Remark               string   `protobuf:"bytes,4,opt,name=remark,proto3" json:"remark,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WeighActionRequest) Reset()         { *m = WeighActionRequest{} }
func (m *WeighActionRequest) String() string { return proto.CompactTextString(m) }
func (*WeighActionRequest) ProtoMessage()    {}
func (*WeighActionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{25}
}

func (m *WeighActionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WeighActionRequest.Unmarshal(m, b)
}
func (m *WeighActionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WeighActionRequest.Marshal(b, m, deterministic)
}
func (m *WeighActionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WeighActionRequest.Merge(m, src)
}
func (m *WeighActionRequest) XXX_Size() int {
	return xxx_messageInfo_WeighActionRequest.Size(m)
}
func (m *WeighActionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_WeighActionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_WeighActionRequest proto.InternalMessageInfo

func (m *WeighActionRequest) GetAccessKey() string {
	if m != nil {
		return m.AccessKey
	}
	return ""
}

func (m *WeighActionRequest) GetTermno() string {
	if m != nil {
		return m.Termno
	}
	return ""
}

func (m *WeighActionRequest) GetAction() string {
	if m != nil {
		return m.Action
	}
	return ""
}

func (m *WeighActionRequest) GetRemark() string {
	if m != nil {
		return m.Remark
	}
	return ""
}

type WeighActionResponse struct {
	Retjson              string   `protobuf:"bytes,1,opt,name=retjson,proto3" json:"retjson,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WeighActionResponse) Reset()         { *m = WeighActionResponse{} }
func (m *WeighActionResponse) String() string { return proto.CompactTextString(m) }
func (*WeighActionResponse) ProtoMessage()    {}
func (*WeighActionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{26}
}

func (m *WeighActionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WeighActionResponse.Unmarshal(m, b)
}
func (m *WeighActionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WeighActionResponse.Marshal(b, m, deterministic)
}
func (m *WeighActionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WeighActionResponse.Merge(m, src)
}
func (m *WeighActionResponse) XXX_Size() int {
	return xxx_messageInfo_WeighActionResponse.Size(m)
}
func (m *WeighActionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_WeighActionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_WeighActionResponse proto.InternalMessageInfo

func (m *WeighActionResponse) GetRetjson() string {
	if m != nil {
		return m.Retjson
	}
	return ""
}

//流水查询
type TransQueryRequest struct {
	Date                 string   `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	TransOffset          int32    `protobuf:"varint,2,opt,name=trans_offset,json=transOffset,proto3" json:"trans_offset,omitempty"`
	TransCount           int32    `protobuf:"varint,3,opt,name=trans_count,json=transCount,proto3" json:"trans_count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TransQueryRequest) Reset()         { *m = TransQueryRequest{} }
func (m *TransQueryRequest) String() string { return proto.CompactTextString(m) }
func (*TransQueryRequest) ProtoMessage()    {}
func (*TransQueryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{27}
}

func (m *TransQueryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransQueryRequest.Unmarshal(m, b)
}
func (m *TransQueryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransQueryRequest.Marshal(b, m, deterministic)
}
func (m *TransQueryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransQueryRequest.Merge(m, src)
}
func (m *TransQueryRequest) XXX_Size() int {
	return xxx_messageInfo_TransQueryRequest.Size(m)
}
func (m *TransQueryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TransQueryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TransQueryRequest proto.InternalMessageInfo

func (m *TransQueryRequest) GetDate() string {
	if m != nil {
		return m.Date
	}
	return ""
}

func (m *TransQueryRequest) GetTransOffset() int32 {
	if m != nil {
		return m.TransOffset
	}
	return 0
}

func (m *TransQueryRequest) GetTransCount() int32 {
	if m != nil {
		return m.TransCount
	}
	return 0
}

type DishTransMain struct {
	Billno               string             `protobuf:"bytes,1,opt,name=billno,proto3" json:"billno,omitempty"`
	Stuempno             string             `protobuf:"bytes,2,opt,name=stuempno,proto3" json:"stuempno,omitempty"`
	Custname             string             `protobuf:"bytes,3,opt,name=custname,proto3" json:"custname,omitempty"`
	Transdate            string             `protobuf:"bytes,4,opt,name=transdate,proto3" json:"transdate,omitempty"`
	Transtime            string             `protobuf:"bytes,5,opt,name=transtime,proto3" json:"transtime,omitempty"`
	DishId               string             `protobuf:"bytes,6,opt,name=dish_id,json=dishId,proto3" json:"dish_id,omitempty"`
	Amount               int32              `protobuf:"varint,7,opt,name=amount,proto3" json:"amount,omitempty"`
	Paymode              string             `protobuf:"bytes,8,opt,name=paymode,proto3" json:"paymode,omitempty"`
	Status               string             `protobuf:"bytes,9,opt,name=status,proto3" json:"status,omitempty"`
	DetailCount          int32              `protobuf:"varint,10,opt,name=detail_count,json=detailCount,proto3" json:"detail_count,omitempty"`
	Refno                string             `protobuf:"bytes,11,opt,name=refno,proto3" json:"refno,omitempty"`
	Expired              string             `protobuf:"bytes,12,opt,name=expired,proto3" json:"expired,omitempty"`
	Details              []*DishTransDetail `protobuf:"bytes,13,rep,name=details,proto3" json:"details,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *DishTransMain) Reset()         { *m = DishTransMain{} }
func (m *DishTransMain) String() string { return proto.CompactTextString(m) }
func (*DishTransMain) ProtoMessage()    {}
func (*DishTransMain) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{28}
}

func (m *DishTransMain) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DishTransMain.Unmarshal(m, b)
}
func (m *DishTransMain) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DishTransMain.Marshal(b, m, deterministic)
}
func (m *DishTransMain) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DishTransMain.Merge(m, src)
}
func (m *DishTransMain) XXX_Size() int {
	return xxx_messageInfo_DishTransMain.Size(m)
}
func (m *DishTransMain) XXX_DiscardUnknown() {
	xxx_messageInfo_DishTransMain.DiscardUnknown(m)
}

var xxx_messageInfo_DishTransMain proto.InternalMessageInfo

func (m *DishTransMain) GetBillno() string {
	if m != nil {
		return m.Billno
	}
	return ""
}

func (m *DishTransMain) GetStuempno() string {
	if m != nil {
		return m.Stuempno
	}
	return ""
}

func (m *DishTransMain) GetCustname() string {
	if m != nil {
		return m.Custname
	}
	return ""
}

func (m *DishTransMain) GetTransdate() string {
	if m != nil {
		return m.Transdate
	}
	return ""
}

func (m *DishTransMain) GetTranstime() string {
	if m != nil {
		return m.Transtime
	}
	return ""
}

func (m *DishTransMain) GetDishId() string {
	if m != nil {
		return m.DishId
	}
	return ""
}

func (m *DishTransMain) GetAmount() int32 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *DishTransMain) GetPaymode() string {
	if m != nil {
		return m.Paymode
	}
	return ""
}

func (m *DishTransMain) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *DishTransMain) GetDetailCount() int32 {
	if m != nil {
		return m.DetailCount
	}
	return 0
}

func (m *DishTransMain) GetRefno() string {
	if m != nil {
		return m.Refno
	}
	return ""
}

func (m *DishTransMain) GetExpired() string {
	if m != nil {
		return m.Expired
	}
	return ""
}

func (m *DishTransMain) GetDetails() []*DishTransDetail {
	if m != nil {
		return m.Details
	}
	return nil
}

type TransQueryResponse struct {
	Trans                []*DishTransMain `protobuf:"bytes,1,rep,name=trans,proto3" json:"trans,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *TransQueryResponse) Reset()         { *m = TransQueryResponse{} }
func (m *TransQueryResponse) String() string { return proto.CompactTextString(m) }
func (*TransQueryResponse) ProtoMessage()    {}
func (*TransQueryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{29}
}

func (m *TransQueryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransQueryResponse.Unmarshal(m, b)
}
func (m *TransQueryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransQueryResponse.Marshal(b, m, deterministic)
}
func (m *TransQueryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransQueryResponse.Merge(m, src)
}
func (m *TransQueryResponse) XXX_Size() int {
	return xxx_messageInfo_TransQueryResponse.Size(m)
}
func (m *TransQueryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TransQueryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TransQueryResponse proto.InternalMessageInfo

func (m *TransQueryResponse) GetTrans() []*DishTransMain {
	if m != nil {
		return m.Trans
	}
	return nil
}

type TransResetDishRequest struct {
	Billno               string   `protobuf:"bytes,1,opt,name=billno,proto3" json:"billno,omitempty"`
	DishId               string   `protobuf:"bytes,2,opt,name=dish_id,json=dishId,proto3" json:"dish_id,omitempty"`
	Termno               string   `protobuf:"bytes,3,opt,name=termno,proto3" json:"termno,omitempty"`
	FoodId               string   `protobuf:"bytes,4,opt,name=food_id,json=foodId,proto3" json:"food_id,omitempty"`
	DeviceSeqno          string   `protobuf:"bytes,5,opt,name=device_seqno,json=deviceSeqno,proto3" json:"device_seqno,omitempty"`
	Amount               int32    `protobuf:"varint,6,opt,name=amount,proto3" json:"amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TransResetDishRequest) Reset()         { *m = TransResetDishRequest{} }
func (m *TransResetDishRequest) String() string { return proto.CompactTextString(m) }
func (*TransResetDishRequest) ProtoMessage()    {}
func (*TransResetDishRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{30}
}

func (m *TransResetDishRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransResetDishRequest.Unmarshal(m, b)
}
func (m *TransResetDishRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransResetDishRequest.Marshal(b, m, deterministic)
}
func (m *TransResetDishRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransResetDishRequest.Merge(m, src)
}
func (m *TransResetDishRequest) XXX_Size() int {
	return xxx_messageInfo_TransResetDishRequest.Size(m)
}
func (m *TransResetDishRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TransResetDishRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TransResetDishRequest proto.InternalMessageInfo

func (m *TransResetDishRequest) GetBillno() string {
	if m != nil {
		return m.Billno
	}
	return ""
}

func (m *TransResetDishRequest) GetDishId() string {
	if m != nil {
		return m.DishId
	}
	return ""
}

func (m *TransResetDishRequest) GetTermno() string {
	if m != nil {
		return m.Termno
	}
	return ""
}

func (m *TransResetDishRequest) GetFoodId() string {
	if m != nil {
		return m.FoodId
	}
	return ""
}

func (m *TransResetDishRequest) GetDeviceSeqno() string {
	if m != nil {
		return m.DeviceSeqno
	}
	return ""
}

func (m *TransResetDishRequest) GetAmount() int32 {
	if m != nil {
		return m.Amount
	}
	return 0
}

type TransResetDishResponse struct {
	Retjson              string   `protobuf:"bytes,1,opt,name=retjson,proto3" json:"retjson,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TransResetDishResponse) Reset()         { *m = TransResetDishResponse{} }
func (m *TransResetDishResponse) String() string { return proto.CompactTextString(m) }
func (*TransResetDishResponse) ProtoMessage()    {}
func (*TransResetDishResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{31}
}

func (m *TransResetDishResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransResetDishResponse.Unmarshal(m, b)
}
func (m *TransResetDishResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransResetDishResponse.Marshal(b, m, deterministic)
}
func (m *TransResetDishResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransResetDishResponse.Merge(m, src)
}
func (m *TransResetDishResponse) XXX_Size() int {
	return xxx_messageInfo_TransResetDishResponse.Size(m)
}
func (m *TransResetDishResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TransResetDishResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TransResetDishResponse proto.InternalMessageInfo

func (m *TransResetDishResponse) GetRetjson() string {
	if m != nil {
		return m.Retjson
	}
	return ""
}

func init() {
	proto.RegisterEnum("WeighingScaleStatus", WeighingScaleStatus_name, WeighingScaleStatus_value)
	proto.RegisterEnum("AgentStatus", AgentStatus_name, AgentStatus_value)
	proto.RegisterEnum("DishBindStatus", DishBindStatus_name, DishBindStatus_value)
	proto.RegisterType((*WeighingScaleLogin)(nil), "WeighingScaleLogin")
	proto.RegisterType((*WeighingScaleLoginResponse)(nil), "WeighingScaleLoginResponse")
	proto.RegisterType((*WeighingScaleHeartBeat)(nil), "WeighingScaleHeartBeat")
	proto.RegisterType((*WeighingParam)(nil), "WeighingParam")
	proto.RegisterType((*WeighingScaleResponse)(nil), "WeighingScaleResponse")
	proto.RegisterType((*BindDishRequest)(nil), "BindDishRequest")
	proto.RegisterType((*BindDishResponse)(nil), "BindDishResponse")
	proto.RegisterType((*UnbindDishRequest)(nil), "UnbindDishRequest")
	proto.RegisterType((*UnbindDishResponse)(nil), "UnbindDishResponse")
	proto.RegisterType((*DishQueryRequest)(nil), "DishQueryRequest")
	proto.RegisterType((*DishQueryResponse)(nil), "DishQueryResponse")
	proto.RegisterType((*TransConfirmRequest)(nil), "TransConfirmRequest")
	proto.RegisterType((*TransConfirmResponse)(nil), "TransConfirmResponse")
	proto.RegisterType((*InitDishRequest)(nil), "InitDishRequest")
	proto.RegisterType((*InitDishResponse)(nil), "InitDishResponse")
	proto.RegisterType((*ConfirmDishRequest)(nil), "ConfirmDishRequest")
	proto.RegisterType((*DishTransDetail)(nil), "DishTransDetail")
	proto.RegisterType((*ConfirmDishResponse)(nil), "ConfirmDishResponse")
	proto.RegisterType((*WeighingScaleEvent)(nil), "WeighingScaleEvent")
	proto.RegisterType((*DownloadFoodRequest)(nil), "DownloadFoodRequest")
	proto.RegisterType((*FoodResponse)(nil), "FoodResponse")
	proto.RegisterType((*DownloadMealRequest)(nil), "DownloadMealRequest")
	proto.RegisterType((*MealResponse)(nil), "MealResponse")
	proto.RegisterType((*DownloadSysParaRequest)(nil), "DownloadSysParaRequest")
	proto.RegisterType((*SysparaResponse)(nil), "SysparaResponse")
	proto.RegisterType((*WeighActionRequest)(nil), "WeighActionRequest")
	proto.RegisterType((*WeighActionResponse)(nil), "WeighActionResponse")
	proto.RegisterType((*TransQueryRequest)(nil), "TransQueryRequest")
	proto.RegisterType((*DishTransMain)(nil), "DishTransMain")
	proto.RegisterType((*TransQueryResponse)(nil), "TransQueryResponse")
	proto.RegisterType((*TransResetDishRequest)(nil), "TransResetDishRequest")
	proto.RegisterType((*TransResetDishResponse)(nil), "TransResetDishResponse")
}

func init() { proto.RegisterFile("agent.proto", fileDescriptor_56ede974c0020f77) }

var fileDescriptor_56ede974c0020f77 = []byte{
	// 2160 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x59, 0x4b, 0x73, 0x23, 0x49,
	0x11, 0x56, 0xeb, 0xad, 0x94, 0x6c, 0xb7, 0xcb, 0x1a, 0xbb, 0xd1, 0xec, 0xc0, 0xd0, 0x01, 0x84,
	0x19, 0x96, 0x36, 0x63, 0xd8, 0xd8, 0x88, 0x25, 0x20, 0xb0, 0xc7, 0x9a, 0x5d, 0xc7, 0xfa, 0x31,
	0xb4, 0x3c, 0x3b, 0xcc, 0x5e, 0x14, 0xe5, 0xee, 0x92, 0xdd, 0x8c, 0xfa, 0x31, 0xfd, 0x98, 0x19,
	0x05, 0x37, 0x0e, 0xdc, 0xb9, 0x70, 0x25, 0xb8, 0x12, 0x70, 0xe3, 0x4f, 0x70, 0xe2, 0xc2, 0xbf,
	0xe0, 0x06, 0x27, 0x0e, 0x44, 0x10, 0xf5, 0x68, 0x75, 0x55, 0x4b, 0xb6, 0xbc, 0x2c, 0xb1, 0x27,
	0x2b, 0xb3, 0xaa, 0xab, 0x32, 0xbf, 0xfc, 0x2a, 0x33, 0xab, 0x0c, 0x5d, 0x7c, 0x45, 0x82, 0xd4,
	0x8a, 0xe2, 0x30, 0x0d, 0xcd, 0x77, 0x80, 0x5e, 0x10, 0xef, 0xea, 0xda, 0x0b, 0xae, 0x46, 0x0e,
	0x9e, 0x92, 0x93, 0xf0, 0xca, 0x0b, 0xd0, 0x36, 0x34, 0x53, 0x12, 0xfb, 0x41, 0x68, 0x68, 0x0f,
	0xb5, 0xdd, 0x8e, 0x2d, 0x24, 0xf4, 0x1e, 0x74, 0x52, 0xcf, 0x27, 0x49, 0x8a, 0xfd, 0xc8, 0xa8,
	0xb2, 0xa1, 0x42, 0x81, 0xde, 0x87, 0x66, 0x92, 0xe2, 0x34, 0x4b, 0x8c, 0xda, 0x43, 0x6d, 0x77,
	0x7d, 0xbf, 0x6f, 0x29, 0x4b, 0x8f, 0xd8, 0x98, 0x2d, 0xe6, 0x98, 0x7f, 0xae, 0xc2, 0x60, 0x71,
	0x6b, 0x9b, 0x24, 0x51, 0x18, 0x24, 0x04, 0x7d, 0x17, 0xf4, 0x64, 0x96, 0xa4, 0xc4, 0x1f, 0x17,
	0x3b, 0x72, 0x63, 0x36, 0xb8, 0xfe, 0x62, 0xbe, 0xef, 0x03, 0x00, 0xec, 0x38, 0x24, 0x49, 0xc6,
	0xaf, 0xc8, 0x2c, 0x37, 0x8b, 0x6b, 0x3e, 0x25, 0x33, 0xf4, 0x18, 0xd6, 0xc4, 0x4a, 0x8a, 0x75,
	0x3d, 0xeb, 0x80, 0xe2, 0x20, 0xac, 0xea, 0xf1, 0x29, 0x5c, 0x42, 0xf7, 0xa1, 0xe3, 0x92, 0x37,
	0x9e, 0x43, 0xc6, 0x9e, 0x6b, 0xd4, 0x1f, 0x6a, 0xbb, 0x0d, 0xbb, 0xcd, 0x15, 0xc7, 0x2e, 0x1d,
	0xbc, 0x26, 0x38, 0x4e, 0xc7, 0x57, 0x38, 0x32, 0x1a, 0x7c, 0x90, 0x29, 0x3e, 0xc6, 0x11, 0xfa,
	0x3a, 0x74, 0x27, 0x61, 0xe8, 0x8e, 0xdf, 0x90, 0x78, 0x1c, 0x84, 0x46, 0x93, 0x1b, 0x43, 0x55,
	0x9f, 0x91, 0xf8, 0x2c, 0xa4, 0xe3, 0x11, 0x8e, 0x71, 0x3e, 0xde, 0x62, 0x9f, 0x77, 0xa8, 0x8a,
	0x8f, 0x1b, 0xd0, 0x8a, 0x49, 0xfa, 0xcb, 0x24, 0x0c, 0x8c, 0x36, 0xfb, 0x36, 0x17, 0xcd, 0x7f,
	0x6a, 0xb0, 0xad, 0xe0, 0xf5, 0x09, 0xdd, 0xf3, 0x90, 0xe0, 0xf4, 0xc6, 0x70, 0xad, 0x00, 0xe6,
	0x0b, 0xc5, 0x0b, 0x3d, 0x84, 0x5e, 0x12, 0x4e, 0xdd, 0x31, 0x73, 0x4f, 0xc0, 0xd2, 0xb1, 0x81,
	0xea, 0x9e, 0x86, 0xa1, 0x7b, 0xec, 0xa2, 0x1f, 0x40, 0xbf, 0x98, 0x91, 0x45, 0x2e, 0x4e, 0x09,
	0x8d, 0x1d, 0xc3, 0xa8, 0x63, 0xa3, 0x7c, 0xe6, 0xf3, 0xf9, 0x08, 0xfa, 0x86, 0x40, 0xeb, 0x2d,
	0xdd, 0x37, 0x65, 0x68, 0x35, 0x6c, 0xa0, 0x2a, 0x66, 0x49, 0x6a, 0x7e, 0x08, 0x6b, 0xb9, 0x4d,
	0xcf, 0x70, 0x8c, 0x7d, 0xa4, 0x43, 0x8d, 0xfa, 0xc2, 0xfd, 0xa4, 0x3f, 0x51, 0x1f, 0x1a, 0x6f,
	0xf0, 0x34, 0x23, 0xc2, 0x3f, 0x2e, 0x98, 0x7f, 0xa8, 0xc1, 0x3d, 0xc5, 0x9b, 0x39, 0xb1, 0x16,
	0xe8, 0xa0, 0xad, 0xa4, 0xc3, 0x32, 0x2e, 0x56, 0x97, 0x73, 0xb1, 0x8c, 0x52, 0xed, 0xce, 0x28,
	0xd5, 0x6f, 0x44, 0xe9, 0x9b, 0x74, 0xcd, 0x49, 0x4a, 0x39, 0x93, 0x78, 0x61, 0x20, 0xf0, 0xec,
	0x52, 0xdd, 0x67, 0x5c, 0xa5, 0x72, 0xb2, 0x79, 0x3b, 0x27, 0x5b, 0x2b, 0x38, 0xd9, 0x2e, 0x73,
	0xb2, 0x0f, 0x0d, 0x3c, 0xc5, 0xb1, 0x6f, 0x74, 0xd8, 0x08, 0x17, 0x64, 0xa6, 0x82, 0xc2, 0x54,
	0xf4, 0x1d, 0x68, 0xd2, 0x8f, 0xfd, 0xc4, 0xe8, 0x3e, 0xac, 0xed, 0x76, 0xf7, 0xd7, 0x2d, 0x25,
	0x86, 0xb6, 0x18, 0x35, 0x7f, 0x53, 0x83, 0x8d, 0x43, 0x2f, 0x70, 0x8f, 0xbc, 0xe4, 0xda, 0x26,
	0xaf, 0x33, 0x92, 0xa4, 0x68, 0x07, 0x5a, 0xae, 0x97, 0x5c, 0x53, 0xe8, 0x04, 0x97, 0xa9, 0x78,
	0xec, 0xa2, 0x01, 0xb4, 0x93, 0x34, 0x23, 0x7e, 0x14, 0x84, 0x02, 0xfb, 0xb9, 0x4c, 0xf9, 0xef,
	0xe0, 0xd8, 0x0d, 0x42, 0x06, 0x77, 0xc3, 0x16, 0x12, 0x4d, 0x57, 0xf4, 0x57, 0x74, 0x3d, 0x9b,
	0xf3, 0xb5, 0x50, 0x50, 0x07, 0x26, 0x84, 0xc4, 0x38, 0x25, 0xe2, 0x14, 0xe7, 0x22, 0x05, 0x1c,
	0x3b, 0x4e, 0x98, 0x05, 0xe9, 0xf8, 0x12, 0x4f, 0xb1, 0x00, 0xb4, 0x2b, 0x74, 0x87, 0x78, 0x8a,
	0xe9, 0xc7, 0xe1, 0x64, 0x32, 0xf5, 0x02, 0xc2, 0xf0, 0x6c, 0xdb, 0xb9, 0x48, 0x0d, 0x75, 0xb2,
	0x24, 0x0d, 0xb0, 0x4f, 0xc4, 0x11, 0x9e, 0xcb, 0xd4, 0xd0, 0x24, 0xcc, 0x62, 0x87, 0x30, 0x28,
	0x3b, 0xb6, 0x90, 0xe8, 0x39, 0x20, 0xef, 0x22, 0x2f, 0x26, 0x63, 0x1a, 0x74, 0x81, 0x27, 0x70,
	0xd5, 0x11, 0xb5, 0xa8, 0x0f, 0x8d, 0x84, 0xbc, 0x0e, 0x42, 0xa3, 0xcb, 0x49, 0xce, 0x84, 0xfc,
	0xdc, 0x7b, 0xae, 0xd1, 0x2b, 0xce, 0x3d, 0xf7, 0x2c, 0xc2, 0x33, 0x3f, 0x74, 0x89, 0xb1, 0xc6,
	0x43, 0x23, 0x44, 0xba, 0x4e, 0x4c, 0x26, 0x41, 0x68, 0xac, 0xf3, 0x75, 0x98, 0x60, 0xfe, 0x55,
	0x03, 0xbd, 0x08, 0x84, 0x38, 0x27, 0xdb, 0xd0, 0xbc, 0xf4, 0xa6, 0xd3, 0x22, 0xa9, 0x70, 0x09,
	0xed, 0x01, 0x5c, 0x7a, 0x81, 0xcb, 0x8f, 0x06, 0x0b, 0xc5, 0xfa, 0xfe, 0x86, 0x45, 0x3f, 0x3d,
	0x9c, 0xab, 0x6d, 0x69, 0x8a, 0x12, 0xb9, 0xda, 0x8d, 0x91, 0xab, 0xdf, 0x1c, 0xb9, 0x46, 0x39,
	0x72, 0x32, 0xc4, 0x4d, 0x15, 0x62, 0xf3, 0x7d, 0xd8, 0x7c, 0x1e, 0x5c, 0xde, 0x91, 0x55, 0xe6,
	0xef, 0x35, 0x40, 0xf2, 0xf4, 0x15, 0xbe, 0xdf, 0x46, 0x42, 0xd9, 0xa8, 0xda, 0x62, 0xdc, 0xb1,
	0x4f, 0xb9, 0x93, 0xbb, 0xc9, 0x25, 0x4a, 0xb4, 0x49, 0x4c, 0x08, 0x63, 0x59, 0xe0, 0xe4, 0x3c,
	0xec, 0x52, 0xdd, 0x21, 0x57, 0x99, 0xdf, 0x03, 0x9d, 0x9a, 0xf6, 0xf3, 0x8c, 0xc4, 0xb3, 0x95,
	0xee, 0xfc, 0x4b, 0x83, 0x4d, 0x69, 0xf6, 0x57, 0xec, 0x8d, 0x01, 0x2d, 0xd5, 0x91, 0x5c, 0x64,
	0xbc, 0xe7, 0x7c, 0x69, 0x0a, 0xde, 0x73, 0x6a, 0x48, 0x44, 0x6d, 0xa9, 0x44, 0x7d, 0x04, 0x2d,
	0x97, 0xa4, 0xd8, 0x9b, 0x26, 0x46, 0x9b, 0x25, 0x11, 0x9d, 0x51, 0xec, 0x22, 0xc6, 0x41, 0x72,
	0xc4, 0x06, 0xec, 0x7c, 0x82, 0xf9, 0x6f, 0x0d, 0xb6, 0xd8, 0xc0, 0x93, 0x30, 0x98, 0x78, 0xb1,
	0xbf, 0x32, 0x97, 0x14, 0x80, 0x54, 0x15, 0x40, 0x1e, 0x00, 0x44, 0x78, 0x36, 0x16, 0xce, 0xd5,
	0xf2, 0x3c, 0x38, 0x3b, 0xe0, 0xfe, 0x7d, 0x1b, 0xd6, 0xc9, 0xbb, 0x94, 0xc4, 0x01, 0x9e, 0x8e,
	0xf9, 0x29, 0xe2, 0x39, 0x65, 0x2d, 0xd7, 0xda, 0x54, 0x89, 0xbe, 0x06, 0x6d, 0xba, 0x8a, 0x9b,
	0x27, 0x16, 0xee, 0x15, 0x3b, 0xc6, 0x62, 0x88, 0xe5, 0xfb, 0xe6, 0x7c, 0x88, 0x56, 0x8f, 0x7c,
	0x6f, 0x91, 0x1e, 0x44, 0x8e, 0x8e, 0xf0, 0x6c, 0xc4, 0x33, 0xc4, 0x36, 0x34, 0x63, 0xe2, 0xe3,
	0xf8, 0x95, 0xc8, 0x29, 0x42, 0x32, 0x2d, 0xe8, 0xab, 0xae, 0xdf, 0x1e, 0x73, 0xf3, 0xef, 0x1a,
	0x6c, 0x1c, 0x07, 0x5e, 0x2a, 0x9f, 0x0e, 0xb5, 0x4d, 0xd0, 0xca, 0x6d, 0x82, 0x04, 0x63, 0x4d,
	0x81, 0x71, 0x07, 0x5a, 0x6a, 0x33, 0xd0, 0x9c, 0xf0, 0x12, 0x57, 0x2a, 0xeb, 0x8d, 0x72, 0x59,
	0xe7, 0x13, 0x62, 0x87, 0x8c, 0x5f, 0x53, 0xa2, 0x32, 0x28, 0xda, 0x74, 0x42, 0xec, 0x10, 0x46,
	0x5d, 0xa9, 0xa3, 0x69, 0x29, 0x1d, 0x4d, 0x91, 0xf1, 0xda, 0x72, 0xc6, 0x33, 0xff, 0x54, 0x05,
	0xbd, 0x70, 0x4b, 0x60, 0x20, 0xf3, 0x5b, 0xbb, 0x85, 0xdf, 0xd5, 0x12, 0xbf, 0xcb, 0xe9, 0xbf,
	0xb6, 0x98, 0xfe, 0x6f, 0x39, 0x02, 0x37, 0xd4, 0x14, 0x03, 0x5a, 0x3e, 0x49, 0x12, 0x7c, 0x35,
	0x8f, 0xbc, 0x10, 0x6f, 0x29, 0x25, 0x45, 0x10, 0xdb, 0x0a, 0x4f, 0x19, 0x11, 0x59, 0xb9, 0xf0,
	0xbd, 0x20, 0x4b, 0x49, 0x22, 0x2a, 0xf3, 0x1a, 0xd7, 0x9e, 0x72, 0xa5, 0x7c, 0xba, 0x40, 0x39,
	0x5d, 0xe6, 0xdf, 0xaa, 0x80, 0x04, 0x63, 0xbe, 0x00, 0x11, 0xfa, 0xd0, 0x88, 0x62, 0xcf, 0xe1,
	0x80, 0x35, 0x6c, 0x2e, 0xfc, 0x0f, 0xf4, 0x78, 0x00, 0x70, 0x99, 0xcd, 0x54, 0x76, 0x74, 0x2e,
	0xb3, 0x99, 0x20, 0x47, 0x81, 0x6d, 0x53, 0xc1, 0xb6, 0x40, 0xa3, 0xa5, 0xa0, 0x81, 0xa0, 0x9e,
	0x05, 0x5e, 0x2a, 0xfa, 0x16, 0xf6, 0x9b, 0x86, 0x50, 0x34, 0xf0, 0xbc, 0x6c, 0xf2, 0x72, 0xdb,
	0xe5, 0xba, 0x11, 0x2b, 0x9e, 0xf7, 0x81, 0xb5, 0x40, 0x63, 0x46, 0x01, 0x8e, 0x4f, 0x9b, 0x2a,
	0xce, 0x44, 0x8a, 0x13, 0xfc, 0xeb, 0x2a, 0xfc, 0xdb, 0x81, 0x16, 0x35, 0x3d, 0xc8, 0x7c, 0x56,
	0x72, 0x1b, 0x76, 0xf3, 0x32, 0x9b, 0x9d, 0x65, 0xbe, 0xf9, 0xeb, 0x2a, 0x6c, 0x94, 0x12, 0x94,
	0x0c, 0x80, 0xa6, 0x00, 0xa0, 0x6c, 0x5d, 0x5d, 0xdc, 0x5a, 0x49, 0x40, 0x92, 0xfb, 0x02, 0x31,
	0x41, 0x39, 0x2e, 0x15, 0x51, 0x69, 0xc8, 0x51, 0xc9, 0x41, 0x69, 0x4a, 0xa0, 0xe8, 0x50, 0x7b,
	0x9d, 0xce, 0xc4, 0x9d, 0x83, 0xfe, 0x94, 0xdc, 0x6c, 0x2b, 0x6e, 0xde, 0x01, 0x3e, 0x04, 0xf5,
	0xc9, 0x14, 0x5f, 0x09, 0xe4, 0xd8, 0x6f, 0xf3, 0x77, 0x1a, 0x6c, 0x29, 0xb4, 0x2a, 0x92, 0x51,
	0x4c, 0x92, 0x6c, 0x9a, 0xe6, 0x38, 0x70, 0x49, 0x3e, 0x13, 0x55, 0xf5, 0x4c, 0xdc, 0xe1, 0x08,
	0x4a, 0x15, 0xa2, 0xbe, 0xaa, 0x42, 0xfc, 0x56, 0x2b, 0x5d, 0x73, 0x87, 0x6f, 0x48, 0x70, 0x17,
	0xbe, 0x13, 0x3a, 0x2f, 0xbf, 0x59, 0x30, 0x41, 0x36, 0xba, 0xa6, 0x1a, 0x5d, 0xdc, 0xa7, 0xea,
	0x77, 0xb8, 0xff, 0xbe, 0x82, 0xad, 0xa3, 0xf0, 0x6d, 0x30, 0x0d, 0x31, 0xeb, 0xf7, 0xef, 0x78,
	0x06, 0x1f, 0x00, 0xe4, 0xbd, 0xfc, 0xbc, 0x7c, 0xe5, 0xad, 0x7c, 0x91, 0x1f, 0xe7, 0x9d, 0x96,
	0x90, 0xcc, 0x8f, 0xa1, 0xc7, 0x37, 0x11, 0x11, 0x51, 0x97, 0xd1, 0xca, 0xcb, 0x48, 0xbd, 0x7d,
	0x55, 0xbd, 0x85, 0x9e, 0x14, 0x56, 0x9f, 0x12, 0x5a, 0xf1, 0xee, 0x64, 0x75, 0x61, 0x56, 0x55,
	0x31, 0x6b, 0x17, 0x7a, 0x7c, 0x15, 0x61, 0x96, 0xb4, 0xaf, 0xa6, 0xee, 0x1b, 0xc2, 0x76, 0xbe,
	0xef, 0x68, 0x96, 0xd0, 0x7b, 0xc4, 0x97, 0xdb, 0xba, 0x7c, 0xe9, 0xa9, 0x95, 0x2e, 0x3d, 0xe6,
	0xa7, 0xb0, 0x31, 0x9a, 0x25, 0x11, 0xdb, 0x48, 0x58, 0x57, 0xfa, 0x44, 0xbb, 0xe5, 0xee, 0x5e,
	0x42, 0xed, 0x57, 0x82, 0x7e, 0x07, 0x4e, 0xea, 0x85, 0xc1, 0x97, 0xb4, 0x9c, 0x26, 0x08, 0xb6,
	0x4e, 0x1e, 0x63, 0x2e, 0x49, 0x2d, 0x42, 0x5d, 0x69, 0x11, 0xf6, 0x60, 0x4b, 0xd9, 0x7c, 0x25,
	0xd6, 0xaf, 0x60, 0x93, 0x9d, 0x22, 0xa5, 0xe7, 0x44, 0x50, 0x67, 0x1d, 0x0d, 0x9f, 0xcb, 0x7e,
	0xd3, 0x53, 0x9a, 0xd2, 0x89, 0xe3, 0x70, 0x32, 0x49, 0x48, 0x2a, 0xea, 0x42, 0x97, 0xe9, 0xce,
	0x99, 0x8a, 0x56, 0x7a, 0x3e, 0xc5, 0x91, 0x52, 0x1a, 0xa4, 0xbc, 0x65, 0xc9, 0x82, 0xd4, 0xfc,
	0x4f, 0x15, 0xd6, 0xe6, 0xe7, 0xf6, 0x14, 0xf3, 0xc7, 0xa7, 0xff, 0x6b, 0xbb, 0xfa, 0x1e, 0x74,
	0xd8, 0x7e, 0xcc, 0x7c, 0x71, 0x0b, 0x9c, 0x2b, 0xe6, 0xa3, 0xd2, 0x4b, 0x45, 0xa1, 0x90, 0x8b,
	0x5b, 0xb3, 0xdc, 0x42, 0x8a, 0x2c, 0xdd, 0x2a, 0x37, 0x00, 0x79, 0xcd, 0x6d, 0xab, 0x1d, 0x6d,
	0xd1, 0x03, 0x77, 0x94, 0x1e, 0x98, 0xe5, 0x5a, 0x9a, 0xa6, 0x04, 0x44, 0xc0, 0x41, 0xe4, 0x3a,
	0x86, 0x51, 0x71, 0x6b, 0xeb, 0x4a, 0xb7, 0x36, 0xba, 0x15, 0xaf, 0xf7, 0xf9, 0xf5, 0x2f, 0x17,
	0xe5, 0xd4, 0xb8, 0xb6, 0x2a, 0x35, 0x7e, 0x04, 0x48, 0x0e, 0xb6, 0x20, 0xc7, 0xb7, 0xa0, 0xc1,
	0x40, 0x30, 0x34, 0x71, 0x83, 0x57, 0x42, 0x64, 0xf3, 0x41, 0xf3, 0x2f, 0x1a, 0xdc, 0x63, 0x4a,
	0x9b, 0x24, 0x44, 0x69, 0x29, 0x6f, 0x8a, 0xa1, 0x84, 0x67, 0xb5, 0x8c, 0xe7, 0xb2, 0xc4, 0x75,
	0x73, 0x13, 0x51, 0x2e, 0x51, 0x8d, 0xc5, 0x12, 0x75, 0x43, 0x23, 0x61, 0xee, 0xc3, 0x76, 0xd9,
	0xea, 0x55, 0x67, 0xe2, 0xd1, 0xe7, 0xe2, 0x10, 0xa9, 0xc9, 0x1c, 0x75, 0xa1, 0x75, 0xfe, 0xf4,
	0xe9, 0xc9, 0xf1, 0xd9, 0x50, 0xaf, 0xa0, 0x0e, 0x34, 0x86, 0xa7, 0xcf, 0x2e, 0x5e, 0xea, 0x1a,
	0x42, 0xb0, 0x7e, 0x7c, 0x36, 0xbe, 0xb0, 0x0f, 0xce, 0x46, 0x07, 0x4f, 0x2e, 0x8e, 0xcf, 0xcf,
	0xf4, 0x2a, 0xea, 0x41, 0xfb, 0x93, 0x17, 0xe3, 0xa1, 0x6d, 0x9f, 0xdb, 0x7a, 0x8d, 0x4e, 0x3e,
	0x38, 0x19, 0xda, 0x17, 0x7a, 0xfd, 0xd1, 0x07, 0xd0, 0x95, 0xde, 0x9e, 0x10, 0x40, 0xf3, 0xc9,
	0xc9, 0xf9, 0x68, 0x78, 0xa4, 0x57, 0x90, 0x0e, 0xbd, 0xd1, 0xcb, 0xd1, 0xc5, 0xf0, 0x54, 0x7c,
	0xa7, 0xa1, 0x36, 0xd4, 0xcf, 0x9f, 0x0d, 0xcf, 0xf4, 0xea, 0xa3, 0xef, 0xc3, 0xba, 0x7a, 0xeb,
	0x46, 0x2d, 0xa8, 0x9d, 0x0d, 0x5f, 0xe8, 0x15, 0xba, 0xfd, 0xc1, 0x89, 0x3d, 0x3c, 0x38, 0x7a,
	0x39, 0x1e, 0xfe, 0xe2, 0x78, 0x74, 0x31, 0xd2, 0xb5, 0xfd, 0x3f, 0xd6, 0x41, 0x67, 0x2e, 0x30,
	0xfb, 0x8f, 0x18, 0x4e, 0xe8, 0xc7, 0xd0, 0xe0, 0x2f, 0xbe, 0x5b, 0xd6, 0xe2, 0x5b, 0xec, 0xe0,
	0xbe, 0x75, 0xf3, 0x03, 0xad, 0x59, 0x41, 0x3f, 0x85, 0x4e, 0xf1, 0x06, 0xb9, 0x63, 0x2d, 0x7f,
	0x9c, 0x1c, 0x6c, 0x5b, 0x4b, 0xdf, 0xe1, 0xcc, 0x0a, 0x7a, 0x0c, 0xed, 0xbc, 0x67, 0x47, 0xba,
	0x55, 0xba, 0x95, 0x0c, 0x36, 0xad, 0x72, 0x43, 0x6f, 0x56, 0xd0, 0x47, 0xd0, 0x95, 0x1a, 0x0c,
	0xb4, 0x65, 0x2d, 0x76, 0xb1, 0x83, 0xbe, 0xb5, 0xa4, 0x07, 0x61, 0xdf, 0x76, 0x86, 0xbe, 0x97,
	0xf2, 0xd2, 0x5f, 0xf2, 0x97, 0x29, 0x6f, 0x31, 0xf5, 0x03, 0xe8, 0xc9, 0xc5, 0x1a, 0xf5, 0xad,
	0x25, 0xb5, 0x7b, 0xb0, 0x66, 0xc9, 0x45, 0x56, 0xfd, 0x8c, 0xd6, 0x39, 0xe9, 0x33, 0xa9, 0x78,
	0x0e, 0xd6, 0x2c, 0xb9, 0x08, 0x32, 0x60, 0x37, 0x4a, 0xc5, 0x0e, 0xed, 0x58, 0xcb, 0xcb, 0xdf,
	0x40, 0xb7, 0x4a, 0x65, 0xca, 0xac, 0xa0, 0x9f, 0xc1, 0xe6, 0xf3, 0x88, 0xce, 0x95, 0xf2, 0x7e,
	0xee, 0xb1, 0x52, 0x82, 0x06, 0x7d, 0x6b, 0x49, 0x69, 0x30, 0x2b, 0xfb, 0xff, 0xa8, 0x02, 0xb0,
	0x17, 0x21, 0x4e, 0x93, 0xc7, 0xd0, 0xce, 0xdf, 0x87, 0x90, 0x6e, 0x95, 0xde, 0xec, 0x06, 0x9b,
	0x56, 0xf9, 0xf1, 0xc8, 0xac, 0xa0, 0x0f, 0x01, 0x8a, 0x87, 0x15, 0x84, 0xac, 0x85, 0x47, 0x99,
	0xc1, 0x96, 0xb5, 0xf8, 0xf2, 0x62, 0x56, 0xd0, 0x4f, 0xa0, 0x27, 0xdf, 0x68, 0x51, 0xdf, 0x5a,
	0x72, 0xb7, 0x1f, 0xdc, 0xb3, 0x96, 0x5d, 0x7b, 0xcd, 0x0a, 0xfa, 0x11, 0x74, 0x58, 0x2a, 0x63,
	0xdb, 0x6e, 0x5a, 0xe5, 0xb7, 0x93, 0x01, 0xb2, 0x16, 0x1e, 0x48, 0xb8, 0xb5, 0x4c, 0xc5, 0x16,
	0x45, 0xc8, 0x5a, 0xa8, 0x7f, 0x83, 0x2d, 0x6b, 0x31, 0x4d, 0x9a, 0x15, 0xf4, 0x04, 0xd6, 0xd5,
	0x5c, 0x82, 0xb6, 0xad, 0xa5, 0x29, 0x71, 0xb0, 0x63, 0x2d, 0x4f, 0x3a, 0x66, 0xe5, 0xf0, 0x18,
	0x0c, 0x27, 0xf4, 0xad, 0x24, 0x8b, 0xde, 0x7a, 0x89, 0x1b, 0xfa, 0x16, 0x6b, 0xed, 0xad, 0xab,
	0x38, 0x72, 0x0e, 0x3b, 0x2c, 0x40, 0xcf, 0x53, 0x6f, 0xfa, 0xb9, 0x59, 0x4c, 0x70, 0x42, 0x7f,
	0x8f, 0x4d, 0x1a, 0xbb, 0xce, 0x1e, 0xfb, 0x7f, 0xce, 0x1e, 0xfb, 0x7f, 0xce, 0x65, 0x93, 0xfd,
	0xf9, 0xe1, 0x7f, 0x03, 0x00, 0x00, 0xff, 0xff, 0x54, 0x55, 0x73, 0x62, 0xe5, 0x19, 0x00, 0x00,
}
